Repository coreweave/ml-containers, pull requests merged in 2024-02, with the labels that each got.

#54 fix(tensorizer): Use `torch-base` base image
  tensorizer/Dockerfile
Labels: enhancement, good first issue

#56 feat(torch): Ubuntu 22.04, Python 3.10, and PyTorch 2.2.0
  .github/configurations/torch-base.yml
  .github/configurations/torch-nccl.yml
  .github/workflows/torch-base.yml
  .github/workflows/torch-extras.yml
  .github/workflows/torch-nccl.yml
  .github/workflows/torch-nightly.yml
  .github/workflows/torch.yml
  docs/README.md
  torch-extras/Dockerfile
  torch/Dockerfile
Labels: enhancement

#57 fix(vllm-tensorizer): Correct workflow yaml for manual workflows and updates to `vllm-tensorizer` container
  .github/workflows/vllm-tensorizer.yml
  vllm-tensorizer/Dockerfile
  vllm-tensorizer/freeze.sh
Labels: bug, enhancement
